### ISSUE TITLE
2010+ results have branch in Circuit Court office name, pre-2010 results don't

### ISSUE THREAD

**Issue by nbdavies** [openelections/openelections-data-wi#22]
There are examples of this inconsistency in our test file.

**Comment by nbdavies** [comment]
I think we were previously leaning towards leaving the Branch # out of the office name, and not treating it as a district, because the branch is not a geographical distinction.

But I ran into a test failure on the 2006-04-04 election caused by this, where multiple rows of the CSV output are considered duplicate, because they have the same ward, office, and candidate name. 

Specifically I'm looking at Milwaukee Circuit Court, which had multiple branches up for election in spring 2006. Milwaukee County has a couple dozen branches total, so it's not surprising they have to elect multiple at a time. Since the branches are geographically delineated, all of Milwaukee County was voting on multiple branches at once. And all of those overlapping races had a candidate called (of course) Scattering.

This might be a good case for including branch number in the office name, or something like that.

**Comment by dwillis** [comment]
@nbdavies I agree - I think for those offices we should include the branch number in the office name.

**Comment by davipo** [comment]
Did you mean we were leaning toward leaving Branch # **in** the office name? That would be my understanding. The first version (2016-07-18) of `parse_office()` removed the Branch number from the office name. That was reversed on 2016-08-10, and has not changed since.

The current `process_xls_2002_to_2010()` assumes a district follows a comma in the office name. Some (all?) of these older files use a comma before a branch number, so these are getting misinterpreted as districts. I think we should be using `parse_office()` to handle office names for these older files. We'll have to check if that will handle district numbers properly.

**Comment by davipo** [comment]
The current `parse_office()` will not handle the district numbers in the office names in the older files, which are formatted differently than in the newer ones. (Typical older office: `US Congress, District No. 6`) I'll try an ad-hoc fix instead.

**Comment by dwillis** [comment]
If I'm reading this right, then offices that have a known geographic component to their "district" should always have a `district` value, but those, like the Milwaukee situation described above, should include the branch in the `office` value. Is that right?

**Comment by davipo** [comment]
I think our standard should be that when the word "District" appears in the office name, we remove it and the following number, and put the number in the district field. Currently, we also remove party names from the office name. In cleaning, we recode office names for consistency, and titlecase them. Otherwise office names are not altered. Is there documentation for the fields in the output files?

**Comment by davipo** [comment]
I fixed this issue on 2017-05-09, and updated the tests to include Branch. Can we close this?

Some Circuit Court office names use a comma before Branch, and some do not. There are examples without commas in our tests for 2016 and 2017. (This should be a new issue, if we want consistency.)
